/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* 870d1c61-2e09-455f-8993-f7858506c22b
*
*/

export const BREAKPOINTS_SM = 160;
export const BREAKPOINTS_MD = 160;
