/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* b3d6e26b-49bc-4aaa-ac14-e1f04066761d
*
*/

export const BREAKPOINTS_XXL = 1440;
export const BREAKPOINTS_XL = 1088;
export const BREAKPOINTS_L = 720;
export const BREAKPOINTS_M = 560;
export const BREAKPOINTS_S = 336;
