/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* 0c2ac4d4-2cac-4025-9bac-d33252d7a29e
*
*/

export const BREAKPOINTS_SM = 160;
export const BREAKPOINTS_MD = 160;
