/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* 9b0e7b28-bcb8-4300-863e-712ebfc81d3e
*
*/

export const THEME_DARK_PURPLE = {
    "colorsPrimary": "#3e2a47",
    "colorsPrimaryLight": "rgb(117.9646017699, 79.9115044248, 135.0884955752)",
    "colorsPrimaryVeryLight": "rgb(144.8761061947, 101.6902654867, 164.3097345133)",
    "colorsPrimaryAlpha": "rgba(62, 42, 71, 0.7)",
    "colorsPrimaryAlphaLight": "rgba(62, 42, 71, 0.5)",
    "colorsSecondary": "#f5f5f5",
    "colorsSecondaryLight": "hsl(0, 0%, 116.0784313725%)",
    "colorsSecondaryVeryLight": "hsl(0, 0%, 126.0784313725%)",
    "colorsSecondaryAlpha": "rgba(245, 245, 245, 0.7)",
    "colorsSecondaryAlphaLight": "rgba(245, 245, 245, 0.5)",
    "colorsContrast": "#ffd700"
}

export const THEME_BLACK_WHITE = {
    "colorsPrimary": "#000000",
    "colorsPrimaryLight": "#333333",
    "colorsPrimaryVeryLight": "rgb(76.5, 76.5, 76.5)",
    "colorsPrimaryAlpha": "rgba(0, 0, 0, 0.7)",
    "colorsPrimaryAlphaLight": "rgba(0, 0, 0, 0.5)",
    "colorsSecondary": "#ffffff",
    "colorsSecondaryLight": "hsl(0, 0%, 120%)",
    "colorsSecondaryVeryLight": "hsl(0, 0%, 130%)",
    "colorsSecondaryAlpha": "rgba(255, 255, 255, 0.7)",
    "colorsSecondaryAlphaLight": "rgba(255, 255, 255, 0.5)",
    "colorsContrast": "#ff6347"
}

export const THEME_BROWN = {
    "colorsPrimary": "#7f5f5f",
    "colorsPrimaryLight": "rgb(175.4054054054, 148.5945945946, 148.5945945946)",
    "colorsPrimaryVeryLight": "rgb(197.2297297297, 177.7702702703, 177.7702702703)",
    "colorsPrimaryAlpha": "rgba(127, 95, 95, 0.7)",
    "colorsPrimaryAlphaLight": "rgba(127, 95, 95, 0.5)",
    "colorsSecondary": "#b0e0e6",
    "colorsSecondaryLight": "rgb(253.4807692308, 254.4038461538, 254.5192307692)",
    "colorsSecondaryVeryLight": "hsl(186.6666666667, 51.9230769231%, 109.6078431373%)",
    "colorsSecondaryAlpha": "rgba(176, 224, 230, 0.7)",
    "colorsSecondaryAlphaLight": "rgba(176, 224, 230, 0.5)",
    "colorsContrast": "#ff4500"
}

export const THEME_PURPLE = {
    "colorsPrimary": "#5a2a83",
    "colorsPrimaryLight": "rgb(142.2543352601, 77.0520231214, 197.9479768786)",
    "colorsPrimaryVeryLight": "rgb(166.7225433526, 115.6705202312, 210.3294797688)",
    "colorsPrimaryAlpha": "rgba(90, 42, 131, 0.7)",
    "colorsPrimaryAlphaLight": "rgba(90, 42, 131, 0.5)",
    "colorsSecondary": "#f0e68c",
    "colorsSecondaryLight": "rgb(251.7692307692, 249.6153846154, 230.2307692308)",
    "colorsSecondaryVeryLight": "hsl(54, 76.9230769231%, 104.5098039216%)",
    "colorsSecondaryAlpha": "rgba(240, 230, 140, 0.7)",
    "colorsSecondaryAlphaLight": "rgba(240, 230, 140, 0.5)",
    "colorsContrast": "#ff6347"
}

export const THEME_LAVENDER = {
    "colorsPrimary": "#8b6e8e",
    "colorsPrimaryLight": "rgb(185.0476190476, 167.0952380952, 186.9047619048)",
    "colorsPrimaryVeryLight": "rgb(207.9166666667, 195.8333333333, 209.1666666667)",
    "colorsPrimaryAlpha": "rgba(139, 110, 142, 0.7)",
    "colorsPrimaryAlphaLight": "rgba(139, 110, 142, 0.5)",
    "colorsSecondary": "#e0ffff",
    "colorsSecondaryLight": "hsl(180, 100%, 113.9215686275%)",
    "colorsSecondaryVeryLight": "hsl(180, 100%, 123.9215686275%)",
    "colorsSecondaryAlpha": "rgba(224, 255, 255, 0.7)",
    "colorsSecondaryAlphaLight": "rgba(224, 255, 255, 0.5)",
    "colorsContrast": "#ff1493"
}

export const THEME_BLUE = {
    "colorsPrimary": "#4682b4",
    "colorsPrimaryLight": "rgb(141.24, 179.16, 210.76)",
    "colorsPrimaryVeryLight": "rgb(177.96, 203.64, 225.04)",
    "colorsPrimaryAlpha": "rgba(70, 130, 180, 0.7)",
    "colorsPrimaryAlphaLight": "rgba(70, 130, 180, 0.5)",
    "colorsSecondary": "#add8e6",
    "colorsSecondaryLight": "rgb(251.1682242991, 253.1775700935, 253.8317757009)",
    "colorsSecondaryVeryLight": "hsl(194.7368421053, 53.2710280374%, 109.0196078431%)",
    "colorsSecondaryAlpha": "rgba(173, 216, 230, 0.7)",
    "colorsSecondaryAlphaLight": "rgba(173, 216, 230, 0.5)",
    "colorsContrast": "#ff4500"
}

export const THEME_TOMATO = {
    "colorsPrimary": "#ff6347",
    "colorsPrimaryLight": "rgb(255, 185.4782608696, 173)",
    "colorsPrimaryVeryLight": "rgb(255, 228.7173913043, 224)",
    "colorsPrimaryAlpha": "rgba(255, 99, 71, 0.7)",
    "colorsPrimaryAlphaLight": "rgba(255, 99, 71, 0.5)",
    "colorsSecondary": "#ffebcd",
    "colorsSecondaryLight": "hsl(36, 100%, 110.1960784314%)",
    "colorsSecondaryVeryLight": "hsl(36, 100%, 120.1960784314%)",
    "colorsSecondaryAlpha": "rgba(255, 235, 205, 0.7)",
    "colorsSecondaryAlphaLight": "rgba(255, 235, 205, 0.5)",
    "colorsContrast": "#4682b4"
}

export const THEME_PINK = {
    "colorsPrimary": "#ffb6c1",
    "colorsPrimaryLight": "hsl(350.9589041096, 100%, 105.6862745098%)",
    "colorsPrimaryVeryLight": "hsl(350.9589041096, 100%, 115.6862745098%)",
    "colorsPrimaryAlpha": "rgba(255, 182, 193, 0.7)",
    "colorsPrimaryAlphaLight": "rgba(255, 182, 193, 0.5)",
    "colorsSecondary": "#faebd7",
    "colorsSecondaryLight": "hsl(34.2857142857, 77.7777777778%, 111.1764705882%)",
    "colorsSecondaryVeryLight": "hsl(34.2857142857, 77.7777777778%, 121.1764705882%)",
    "colorsSecondaryAlpha": "rgba(250, 235, 215, 0.7)",
    "colorsSecondaryAlphaLight": "rgba(250, 235, 215, 0.5)",
    "colorsContrast": "#4682b4"
}

