/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* d6241124-255d-43ef-a065-2a7ea279c48f
*
*/

export const DISTANCES_VERY_SMALL = 8;
export const DISTANCES_SMALL = 16;
export const DISTANCES_MEDIUM = 32;
export const DISTANCES_BIG = 48;
export const DISTANCES_LARGE = 64;
