/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* d2015314-80e9-441c-839a-10976d84cfbe
*
*/

export const DISTANCES_VERY_SMALL = 8;
export const DISTANCES_SMALL = 16;
export const DISTANCES_MEDIUM = 32;
export const DISTANCES_BIG = 48;
export const DISTANCES_LARGE = 64;
