/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* e4345aad-df2d-40f5-a047-6fdd1022a120
*
*/

export const DISTANCES_VERY_SMALL = 8;
export const DISTANCES_SMALL = 16;
export const DISTANCES_MEDIUM = 32;
export const DISTANCES_BIG = 48;
export const DISTANCES_LARGE = 64;
