/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* ac935939-674e-4cc9-82dc-d8d8ccec42ec
*
*/

export const BREAKPOINTS_SM: string = "10rem";
export const BREAKPOINTS_MD: string = "10rem";
