/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* 98a59029-2c75-4609-9211-216de8bc328b
*
*/

export const DISTANCES_VERY_SMALL: string = "0.5rem";
export const DISTANCES_SMALL: string = "1rem";
export const DISTANCES_MEDIUM: string = "2rem";
export const DISTANCES_BIG: string = "3rem";
export const DISTANCES_LARGE: string = "4rem";
