/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* e056c4d3-287c-472e-bd2c-bd1fe795a29f
*
*/

export const BREAKPOINTS_SM: string = "10rem";
export const BREAKPOINTS_MD: string = "10rem";
