/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* 70a78aba-22fe-4ffd-baed-36a96efef2f2
*
*/

export const BREAKPOINTS_SM: string = "10rem";
export const BREAKPOINTS_MD: string = "10rem";
