/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* 7b8c6480-3081-4957-afdd-c66520172518
*
*/

export const DISTANCES_VERY_SMALL: string = "0.5rem";
export const DISTANCES_SMALL: string = "1rem";
export const DISTANCES_MEDIUM: string = "2rem";
export const DISTANCES_BIG: string = "3rem";
export const DISTANCES_LARGE: string = "4rem";
