/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* da0edcb5-d3b9-4b72-b069-16926bf3a24d
*
*/

export const FONTS_PRIMARY: string = "'lato', 'sans-serif'";
export const FONTS_SECONDARY: string = "'Merriweather', 'serif'";
export const FONTS_SIZE_SMALL: string = "0.85rem";
export const FONTS_SIZE_BASE: string = "1rem";
export const FONTS_SIZE_MD: string = "1.2rem";
export const FONTS_SIZE_LG: string = "1.3rem";
export const FONTS_SIZE_XL: string = "2rem";
export const FONTS_SIZE_XXL: string = "2.5rem";
export const FONTS_SIZE_XXL2: string = "6rem";
export const FONTS_SIZE_XXL3: string = "10rem";
export const FONTS_SIZE_XXL4: string = "20rem";
export const FONTS_REGULAR: number = 300;
export const FONTS_BOLD: number = 600;
export const FONTS_EXTRA_BOLD: number = 900;
export const FONTS_LINE_HEIGHT_SM: number = 1;
export const FONTS_LINE_HEIGHT_MD: number = 1.2;
export const FONTS_LINE_HEIGHT_LG: number = 1.3;
export const FONTS_LINE_HEIGHT_XL: number = 1.5;
