/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* 8d9f0969-4ccd-4d08-8363-6fde484a24db
*
*/

export const BREAKPOINTS_SM = 160;
export const BREAKPOINTS_MD = 160;
