/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* 2ea9b92f-58aa-4c45-9339-28891debaa4b
*
*/

export const DISTANCES_VERY_SMALL = 8;
export const DISTANCES_SMALL = 16;
export const DISTANCES_MEDIUM = 32;
export const DISTANCES_BIG = 48;
export const DISTANCES_LARGE = 64;
