/*
*
* WARNING: Any changes here could get overriden.
* This file was autogenerated.
*
* f0aa42c7-5d93-4f07-8f17-cdc3954ad871
*
*/

export const FONTS_PRIMARY = "'lato', 'sans-serif'";
export const FONTS_SECONDARY = "'Merriweather', 'serif'";
export const FONTS_SIZE_SMALL = 13.6;
export const FONTS_SIZE_BASE = 16;
export const FONTS_SIZE_MD = 19.2;
export const FONTS_SIZE_LG = 20.8;
export const FONTS_SIZE_XL = 32;
export const FONTS_SIZE_XXL = 40;
export const FONTS_SIZE_XXL2 = 96;
export const FONTS_SIZE_XXL3 = 160;
export const FONTS_SIZE_XXL4 = 320;
export const FONTS_REGULAR = "300";
export const FONTS_BOLD = "600";
export const FONTS_EXTRA_BOLD = "900";
export const FONTS_LINE_HEIGHT_SM = "1";
export const FONTS_LINE_HEIGHT_MD = "1.2";
export const FONTS_LINE_HEIGHT_LG = "1.3";
export const FONTS_LINE_HEIGHT_XL = "1.5";
