name: Main Pipeline

env:
    HUSKY: 0

on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    dependency-review:
        uses: ./.github/workflows/dependency-review.yml

    run-tests:
        uses: ./.github/workflows/unit-tests.yml

    sonarcloud:
        uses: ./.github/workflows/sonarcloud.yml
        secrets:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
