name: Setup pnpm

on:
    workflow_call:

jobs:
    cache-and-install:
        name: Cache and install pnpm
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  version: 8.11.0
                  run_install: false
                  dest: ~/setup-pnpm

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 23.6.0
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install
