name: Unit tests

on: push

jobs:
    test:
        name: Run unit tests
        runs-on: ubuntu-latest

        steps:
            - name: Git checkout
              uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v4.1.0

            - name: Install modules
              run: pnpm i

            - name: Testing
              run: pnpm test
