name: Unit tests

on:
    workflow_call:

jobs:
    test:
        name: Run unit tests
        runs-on: ubuntu-latest

        steps:
            - name: Git checkout
              uses: actions/checkout@v3

            - uses: pnpm/action-setup@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20.0.0
                  cache: "pnpm"

            - name: Restore pnpm store
              uses: actions/cache@v4
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Recreate symlinks (no re-download)
              run: pnpm install --frozen-lockfile

            - name: Testing
              run: pnpm test
