name: Unit tests

on:
    workflow_call:

jobs:
    test:
        name: Run unit tests
        runs-on: ubuntu-latest

        steps:
            - name: Git checkout
              uses: actions/checkout@v3

            - name: Testing
              run: pnpm test
