name: Unit tests

on:
    workflow_call:

jobs:
    test:
        name: Run unit tests
        runs-on: ubuntu-latest

        steps:
            - name: Git checkout
              uses: actions/checkout@v3

            - uses: pnpm/action-setup@v4
              name: Install pnpm
              with:
                  run_install: true

            - name: Testing
              run: pnpm all:test
